import os, sys

includes = ['../../include']
sourcedirs = ['.']
files = Glob("*.c")
for d in sourcedirs:
	files += Glob(d + '/*.c')
libs = ['zocle']
defs = ['_REENTRANT', '_GNU_SOURCE']
libpath = ['../../']
if sys.platform == 'linux2':
	ldflags = '-Wl,-R../../'
else:
	ldflags = ''

env = Environment(CCFLAGS='-ggdb -Wall', CPPDEFINES=defs, CPPPATH=includes, 
				  LIBPATH=libpath, LIBS=libs, LINKFLAGS=ldflags)

for fn in files:
	env.Program(fn)
