import os, sys, glob

includes = ['../../include']
sourcedirs = ['.']
files = glob.glob("*.c")
for d in sourcedirs:
	files += glob.glob(d + '/*.c')
libs = ['iconv', 'pcre', 'zocle', 'mysqlclient']
#libs = []
defs = ['_REENTRANT', '_GNU_SOURCE', 'ZOCLE_WITH_PCRE','ZOCLE_WITH_ICONV']
libpath = ['../../', '/opt/mysql/lib']
if sys.platform == 'linux2':
	ldflags = '-Wl,-R../../'
else:
	ldflags = ''

env = Environment(CCFLAGS='-ggdb -Wall -std=gnu99', CPPDEFINES=defs, CPPPATH=includes, 
				  LIBPATH=libpath, LIBS=libs, LINKFLAGS=ldflags)

for fn in files:
	#env.Program(fn[:-2], [fn])
	env.Program(fn[:-2], [fn, '../../libzocle.a'])
