import os, sys, glob

includes = ['../../include']
sourcedirs = ['.']
files = glob.glob("*.c")
for d in sourcedirs:
	files += glob.glob(d + '/*.c')
#libs = ['zocle2', 'pcre']
libs = ['iconv', 'pcre']
defs = ['_REENTRANT', '_GNU_SOURCE', 'ZOCLE_WITH_PCRE','ZOCLE_WITH_ICONV']
libpath = ['../../']
if sys.platform == 'linux2':
	ldflags = '-Wl,-R../../ -pg'
else:
	ldflags = '-pg'

env = Environment(CCFLAGS='-Wall -ggdb -std=gnu99', CPPDEFINES=defs, CPPPATH=includes, 
				  LIBPATH=libpath, LIBS=libs, LINKFLAGS=ldflags)

for fn in files:
	#env.Program(fn[:-2], [fn])
	#env.Program(fn[:-2], [fn, '/usr/local/lib/libtcmalloc_minimal.a'])
	env.Program(fn[:-2], [fn, '../../libzocle2.a'])
