import os, sys
import glob

includes = ['../../include']
sourcedirs = ['.']
files = glob.glob("*.c")
for d in sourcedirs:
	files += Glob(d + '/*.c')
#libs = ['zocle2', 'pthread']
libs = ['pthread']
defs = ['_REENTRANT', '_GNU_SOURCE']
libpath = ['../../']
if sys.platform == 'linux2':
	ldflags = '-Wl,-R../../'
else:
	ldflags = ''

env = Environment(CCFLAGS='-ggdb -Wall', CPPDEFINES=defs, CPPPATH=includes, 
				  LIBPATH=libpath, LIBS=libs, LINKFLAGS=ldflags)

for fn in files:
	fname = str(fn)[:-2]
	env.Program(fname, [fn, '../../libzocle.a'])
