import os, sys

includes = ['../../include', '/usr/local/mysql/include', '/opt/mysql/include', '/usr/include/mysql']
sourcedirs = ['.']
files = Glob("*.c")
for d in sourcedirs:
	files += Glob(d + '/*.c')
#libs = []
libs = ['zocle', 'sqlite3', 'mysqlclient']
defs = ['_REENTRANT', '_GNU_SOURCE', 'ZOCLE_WITH_SQLITE', 'ZOCLE_WITH_MYSQL']
libpath = ['../../', '/usr/local/mysql/lib', '/opt/mysql/lib']
if sys.platform == 'linux2':
	ldflags = '-Wl,-R../../'
else:
	ldflags = ''

env = Environment(CCFLAGS='-ggdb -Wall -std=gnu99', CPPDEFINES=defs, CPPPATH=includes, 
				  LIBPATH=libpath, LIBS=libs, LINKFLAGS=ldflags)

for fn in files:
	env.Program(fn)
