import os, sys, glob

includes = ['../../include']
files = glob.glob("*.c")
libs = ['ssl', 'crypto', 'iconv']
defs = ['_REENTRANT', '_GNU_SOURCE', 'ZOCLE_WITH_SSL']
#defs = ['_REENTRANT', '_GNU_SOURCE']
libpath = ['../../', '/usr/local/lib']
if sys.platform == 'linux2':
	ldflags = '-Wl,-R../../'
else:
	ldflags = ''

env = Environment(CCFLAGS='-ggdb -Wall', CPPDEFINES=defs, CPPPATH=includes, 
				  LIBPATH=libpath, LIBS=libs, LINKFLAGS=ldflags)

for fn in files:
	env.Program([fn, '../../libzocle.a'])
