import os, sys, glob

includes = ['../../include']
sourcedirs = ['.']
files = glob.glob("*.c")
for d in sourcedirs:
	files += glob.glob(d + '/*.c')
#libs = ['zocle2', 'pcre']
libs = ['iconv', 'pcre', 'zocle2', 'z', 'c', 'ev', 'zocle2']
defs = ['_REENTRANT', '_GNU_SOURCE', 'ZOCLE_WITH_PCRE','ZOCLE_WITH_ICONV', 
		'ZOCLE_WITH_LIBEV', 'ZOCLE_WITH_SSL']
libpath = ['../../']
if sys.platform == 'linux2':
	ldflags = '-Wl,-R../../'
else:
	ldflags = ''

env = Environment(CCFLAGS='-ggdb -Wall -std=gnu99', CPPDEFINES=defs, CPPPATH=includes, 
				  LIBPATH=libpath, LIBS=libs, LINKFLAGS=ldflags)

for fn in files:
	env.Program(fn[:-2], [fn])
	#env.Program(fn[:-2], [fn, '../../libzocle2.a'])
